default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Meme_Generator_Backend
  host: localhost
  port: 5432

production:
  <<: *default
  database: Meme_Generator_Backend_prod
  username: yourusername # change
  password: <%= ENV['XXX_DATABASE_PASSWORD'] %> # change

# This database is erased and regenerated on testing.
# Don't point it to the same database as dev or prod.
test:
  <<: *default
  database: Meme_Generator_Backend_test
